the_babysitter = "The boys can watch an hour of <adjective> television before turning off the <plural noun> in their room. Make sure they do not watch any violent <plural noun> or adult <plural noun>. If there are any phone <plural noun>, do not identify yourself as the <noun> sitter. Take a message. Write it <adverb> on the <noun> provided."
the_miner = "Once upon a time, a miner named Thabo worked in a big <PLACE>. Every day, he woke up early to <VERB> for shiny diamonds deep in the ground. Thabo’s helmet was <ADJECTIVE>, and his boots were covered in dirt. He used his pickaxe to <VERB> through the tough rock, and he never gave up. One day, Thabo found a diamond that sparkled so brightly it made the <PLACE> look magical. He was excited <CONJUNCTION> a little nervous because it was the biggest diamond he had ever seen. He placed the diamond in his bag <ADVERB> so it wouldn’t get scratched. When Thabo returned to the surface, he shared the news with his team, and everyone cheered. They knew their hard work had paid off, and Thabo felt <ADJECTIVE> as he walked home."
wedding_vows = "I, <MOVIE CHARACTER NAME>, choose you, <TV CHARACTER NAME>, to be my spouse for life. Together, we’ll face the ups and <PLURAL DIRECTION>, always by each other’s side. I offer you my <BODY PART> and <BODY ORGAN> as a safe haven filled with love and <NOUN>. I promise to stay <ADJECTIVE> and devoted to you. Like this never-ending <SHAPE>, my love for you will endure <AMOUNT OF TIME>. Just as this ring is made of <ADJECTIVE> material, my commitment to you will never <VERB>. With this ring, I <VERB> you."
look_it_up = "A/An <ADJECTIVE> dictionary is the essential reference for home, school, or <NOUN>. A dictionary not only defines <PLURAL NOUN>, but tells you how to spell words and how to pronounce them <ADVERB>. Dictionaries are available in local <NOUN> stores or, if necessary, you can order one with a/an <NOUN> card over the Internet. For the average <NOUN>, a medium-sized dictionary is best. For researchers, an unabridged <NOUN>, which has more than 200,000 <PLURAL NOUN>, will be needed. For those who can’t remember the meaning of any <PLURAL NOUN>, a pocket-sized dictionary works <ADVERB>. These dictionaries are small enough to fit in a woman’s <NOUN>, the pocket of a man’s <NOUN>, or a kid’s back <NOUN>. As Henry Wadsworth Longefellow, the famous , wrote, “I’d rather go without food in my <NOUN> than go without a dictionary on my <NOUN> shelf.”"
visiting_china = "When <PERSON'S NAME> was <AGE>, her parents told her they were going on a trip to China. They told her to pack her <NOUN>. The plane ride was <NUMBER> hours long! She <PAST TENSE VERB> and <PAST TENSE VERB>. When they got to China, she was very <ADJECTIVE>. On their trip, they visited <PLACE>, <PLACE>, and <PLACE>. They ate a lot of interesting things, including <ADJECTIVE> <FOOD>, <ADJECTIVE> <FOOD>, and <DRINK>. Everyone had a/an <ADJECTIVE> time. When it was time to go home, she was very <ADJECTIVE>. ”Can't we stay longer?” she said."
going_to_the_doctor = "Every year, you should go visit the doctor. It is a very <ADJECTIVE> visit. Usually, you have to skip going to <PLACE> to go. Your doctor is usually a/an <ADJECTIVE> man or woman who is wearing a/an <ADJECTIVE> <PIECE OF CLOTHING>. They will look at your <BODY PART>, <BODY PART>, and <BODY PART>. Sometimes, they can be very <ADJECTIVE>. Afterwards, they will give you a <NOUN> and a <NOUN> and your mom or dad will take you to <PLACE> as a treat. All in all, the doctor's office isn't so <ADJECTIVE>!"

DEFAULT_TEMPLATES = {
    "the babysitter": the_babysitter,
    "the miner": the_miner,
    "wedding vows": wedding_vows,
    "look it up": look_it_up,
    "visiting china": visiting_china,
    "going to the doctor": going_to_the_doctor,
}